---
title: "Arbeidskrav 1 - SOK 1005"
format: html
editor: visual
---

```{r, warning=FALSE, message=FALSE}
rm(list=ls())

#getting packages
library(readr)
library(tidyverse)
library(lubridate)
library(zoo)

#Lower Troposphere
temp_lt <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt")

#Mid-Troposphere
temp_mt <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/tmt/uahncdc_mt_6.0.txt")

#Tropopause
temp_tp <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/ttp/uahncdc_tp_6.0.txt")

#Lower Stratosphere
temp_ls <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/tls/uahncdc_ls_6.0.txt")
```

```{r}
#Dynamic select of years, removing rows that we are not interested in
temp_ls <- temp_ls[1:which(temp_ls$Year %in% "Year")-1, ]
temp_lt <- temp_lt[1:which(temp_lt$Year %in% "Year")-1, ] 
temp_mt <- temp_mt[1:which(temp_mt$Year %in% "Year")-1, ] 
temp_tp <- temp_tp[1:which(temp_tp$Year %in% "Year")-1, ] 
```

```{r}

temp_ls <- temp_ls %>% 
  mutate_if(is.character, ~as.numeric(.)) %>% #The content of the dataframe is chr, so i change everything to numeric
  mutate(Date=ym(paste(Year, Mo))) %>% #Making a new column with both date and year
  select(Date, Year, Globe) %>% #Selecting the columns that we are interested in
  mutate(Average_ls = rollmean(Globe, 12,  fill=NA, align="right")) # making a right aligned rolling average

temp_lt <- temp_lt %>% 
  mutate_if(is.character, ~as.numeric(.)) %>% 
  mutate(Date=ym(paste(Year, Mo))) %>% 
  select(Date, Year, Globe) %>% 
  mutate(Average_lt = rollmean(Globe, 12,  fill=NA, align="right"))

temp_mt <- temp_mt %>% 
  mutate_if(is.character, ~as.numeric(.)) %>% 
  mutate(Date=ym(paste(Year, Mo))) %>% 
  select(Date, Year, Globe) %>% 
  mutate(Average_mt = rollmean(Globe, 12,  fill=NA, align="right"))

temp_tp <- temp_tp %>% 
  mutate_if(is.character, ~as.numeric(.)) %>% 
  mutate(Date=ym(paste(Year, Mo))) %>% 
  select(Date, Year, Globe) %>% 
  mutate(Average_tp = rollmean(Globe, 12,  fill=NA, align="right"))

```

```{r}
df_average <- temp_ls %>%
  select(-Globe) %>% #removing Globe data as we dont need it for the plot
  cbind(Average_lt = temp_lt$Average_lt,
        Average_mt = temp_mt$Average_mt,
        Average_tp = temp_tp$Average_tp)
#binding the average of the values we need to the main dataframe

df_average <- df_average %>% 
  mutate(Average = (Average_ls + Average_lt + Average_mt + Average_tp)/4)
#Making the average of the four different locations with their average


```

```{r}
df_average %>% 
  filter(Year >=1980) %>% 
  ggplot(aes(x=Date))+
  geom_line(aes(y=Average_lt, color="Low Troposphere"))+#color adds to legend
  geom_line(aes(y=Average_mt, color="Mid-Troposphere"))+
  geom_line(aes(y=Average_tp, color="Tropopause"))+
  geom_line(aes(y=Average_ls, color="Lower Stratosphere"))+
  geom_line(aes(y=Average, color="Average"), size=1.2)+
  labs(
  color="Position in the atmosphere", 
  title="Temperature change in the atmosphere over time", 
  y="Temperature (Celsius)", 
  x="Year", 
  subtitle="Temperature average of the four locations in the atmosphere, 
Average of all four, 1980->"
  )
#Plotting by adding the Main average and the other average
#labs command lets me add name of legend, title and the y axis
```

``` {"))}
  
```
